
import __ASTRO_IMAGE_IMPORT_Z23j8zj from "../../assets/images/same_subagents_10s.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md";
import __ASTRO_IMAGE_IMPORT_Z1sWqCj from "../../assets/images/different_subagents_long_7s.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md";
import __ASTRO_IMAGE_IMPORT_1jrWb2 from "../../assets/images/serial_execution_plan.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md";
import __ASTRO_IMAGE_IMPORT_Z24jzgN from "../../assets/images/different_subagents_short.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md";
import __ASTRO_IMAGE_IMPORT_Zi68KB from "../../assets/images/code_reviewer_subagent_report.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md";
import __ASTRO_IMAGE_IMPORT_Z1a2FDH from "../../assets/images/context_usage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md";
import __ASTRO_IMAGE_IMPORT_Z2s6kSy from "../../assets/images/claude-custom-agents.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md";
export default new Map([["../../assets/images/same_subagents_10s.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md", __ASTRO_IMAGE_IMPORT_Z23j8zj], ["../../assets/images/different_subagents_long_7s.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md", __ASTRO_IMAGE_IMPORT_Z1sWqCj], ["../../assets/images/serial_execution_plan.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md", __ASTRO_IMAGE_IMPORT_1jrWb2], ["../../assets/images/different_subagents_short.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md", __ASTRO_IMAGE_IMPORT_Z24jzgN], ["../../assets/images/code_reviewer_subagent_report.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md", __ASTRO_IMAGE_IMPORT_Zi68KB], ["../../assets/images/context_usage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md", __ASTRO_IMAGE_IMPORT_Z1a2FDH], ["../../assets/images/claude-custom-agents.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoing-beyond-basics-claude-code-custom-agents.md", __ASTRO_IMAGE_IMPORT_Z2s6kSy]]);
		